version: "3.9"

name: "compress-ai-prod"

services:
  fe:
    container_name: fe
    image: react-prod:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"

  model:
    container_name: model
    image: flask:latest
    build:
      context: ./model-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
