version: "3.9"

name: "brainycompress"

services:
  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"

  model-server:
    container_name: model-server
    image: model-server:latest
    build:
      context: ./model-server
      dockerfile: Dockerfile
    volumes:
      - ./model-server/pretrained-model:/app/pretrained-model
    ports:
      - "50051:50051"

  forwarder:
    container_name: forwarder
    image: forwarder:latest
    build:
      context: ./forwarder
      dockerfile: Dockerfile
    volumes:
      - ./forwarder/config:/app/config
    ports:
      - "5000:5000"
    depends_on:
      - model-server
