// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: protos/compress.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageCompressServiceClient is the client API for ImageCompressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageCompressServiceClient interface {
	CompressOneImage(ctx context.Context, in *CompressOneFileRequest, opts ...grpc.CallOption) (*CompressOneFileResponse, error)
}

type imageCompressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageCompressServiceClient(cc grpc.ClientConnInterface) ImageCompressServiceClient {
	return &imageCompressServiceClient{cc}
}

func (c *imageCompressServiceClient) CompressOneImage(ctx context.Context, in *CompressOneFileRequest, opts ...grpc.CallOption) (*CompressOneFileResponse, error) {
	out := new(CompressOneFileResponse)
	err := c.cc.Invoke(ctx, "/compress_model.ImageCompressService/CompressOneImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageCompressServiceServer is the server API for ImageCompressService service.
// All implementations must embed UnimplementedImageCompressServiceServer
// for forward compatibility
type ImageCompressServiceServer interface {
	CompressOneImage(context.Context, *CompressOneFileRequest) (*CompressOneFileResponse, error)
	mustEmbedUnimplementedImageCompressServiceServer()
}

// UnimplementedImageCompressServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImageCompressServiceServer struct {
}

func (UnimplementedImageCompressServiceServer) CompressOneImage(context.Context, *CompressOneFileRequest) (*CompressOneFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompressOneImage not implemented")
}
func (UnimplementedImageCompressServiceServer) mustEmbedUnimplementedImageCompressServiceServer() {}

// UnsafeImageCompressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageCompressServiceServer will
// result in compilation errors.
type UnsafeImageCompressServiceServer interface {
	mustEmbedUnimplementedImageCompressServiceServer()
}

func RegisterImageCompressServiceServer(s grpc.ServiceRegistrar, srv ImageCompressServiceServer) {
	s.RegisterService(&ImageCompressService_ServiceDesc, srv)
}

func _ImageCompressService_CompressOneImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompressOneFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageCompressServiceServer).CompressOneImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compress_model.ImageCompressService/CompressOneImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageCompressServiceServer).CompressOneImage(ctx, req.(*CompressOneFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageCompressService_ServiceDesc is the grpc.ServiceDesc for ImageCompressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageCompressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compress_model.ImageCompressService",
	HandlerType: (*ImageCompressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompressOneImage",
			Handler:    _ImageCompressService_CompressOneImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/compress.proto",
}
