# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63lassify.proto\x12\x14\x63lassification_model\"g\n\x17\x43lassifyOneImageRequest\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x12\n\nimage_name\x18\x02 \x01(\t\x12\x12\n\nimage_type\x18\x03 \x01(\t\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\"Q\n\x18\x43lassifyOneImageResponse\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\x02\x32\x8a\x01\n\x15\x43lassificationService\x12q\n\x10\x43lassifyOneImage\x12-.classification_model.ClassifyOneImageRequest\x1a..classification_model.ClassifyOneImageResponseB\tZ\x07./modelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./model'
  _CLASSIFYONEIMAGEREQUEST._serialized_start=40
  _CLASSIFYONEIMAGEREQUEST._serialized_end=143
  _CLASSIFYONEIMAGERESPONSE._serialized_start=145
  _CLASSIFYONEIMAGERESPONSE._serialized_end=226
  _CLASSIFICATIONSERVICE._serialized_start=229
  _CLASSIFICATIONSERVICE._serialized_end=367
# @@protoc_insertion_point(module_scope)
