# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import compress_pb2 as compress__pb2


class ImageCompressServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompressOneImage = channel.unary_unary(
                '/compress_model.ImageCompressService/CompressOneImage',
                request_serializer=compress__pb2.CompressOneFileRequest.SerializeToString,
                response_deserializer=compress__pb2.CompressOneFileResponse.FromString,
                )


class ImageCompressServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CompressOneImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageCompressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompressOneImage': grpc.unary_unary_rpc_method_handler(
                    servicer.CompressOneImage,
                    request_deserializer=compress__pb2.CompressOneFileRequest.FromString,
                    response_serializer=compress__pb2.CompressOneFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'compress_model.ImageCompressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageCompressService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CompressOneImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compress_model.ImageCompressService/CompressOneImage',
            compress__pb2.CompressOneFileRequest.SerializeToString,
            compress__pb2.CompressOneFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
