# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import classify_pb2 as classify__pb2


class ClassificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyOneImage = channel.unary_unary(
                '/classification_model.ClassificationService/ClassifyOneImage',
                request_serializer=classify__pb2.ClassifyOneImageRequest.SerializeToString,
                response_deserializer=classify__pb2.ClassifyOneImageResponse.FromString,
                )


class ClassificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClassifyOneImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyOneImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyOneImage,
                    request_deserializer=classify__pb2.ClassifyOneImageRequest.FromString,
                    response_serializer=classify__pb2.ClassifyOneImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'classification_model.ClassificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClassificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClassifyOneImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/classification_model.ClassificationService/ClassifyOneImage',
            classify__pb2.ClassifyOneImageRequest.SerializeToString,
            classify__pb2.ClassifyOneImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
